#!/usr/bin/expect -f

#set force_conservative 1  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
#if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
#}

set timeout -1 
set stty_init "rows 51 columns 66"
spawn mono OpenSim.exe -console=rest
match_max 100000
trap {exp_send -- "shutdown"} {SIGTERM}
expect eof
